name: Python CD
 
on:
  push:
    branches: [ main ]

jobs:
  delivery:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Rodar análise com pylint
      run: |
        pylint seu_script.py

    - name: Simular entrega (execução do script)
      run: |
        echo "Simulando entrega em produção"
        python seu_script.py << EOF
        10
        EOF
