name: Python CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3
      
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        
    - name: Análise de código com pylint
      run: |
        pylint main.py

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3
      
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        
    - name: Rodar análise com pylint
      run: |
        pylint main.py
        
    - name: Simular entrega (execução do script)
      run: |
        echo "Simulando entrega em produção"
        python main.py << EOF
        10
        EOF